package eu.theritual.wrathofbahrott.dataoperator.gameenums;

public enum GamePicture {
    MENU_BACKGROUND, GAME_BACKGROUND, WOB_LOGO, EXIT_ON, EXIT_OUT, START_ON, START_OUT,
    CREDITS_ON, CREDITS_OUT, OPTIONS_ON, OPTIONS_OUT, SUBMENU_BACKGROUND, EYE_ICON, BIG_TILE_TEXTURE
}