package eu.theritual.wrathofbahrott.dataoperator.gameenums;

public enum MapElement {
    GRASS1_SQUARE, GRASS1_HOLE,
    GRASS2_SQUARE, GRASS2_HOLE,
    GRASS3_SQUARE, GRASS3_HOLE,
    SAND1, SAND2, SAND3,
    STONE_FLOOR, SCOTT_FLOOR, EGYPT_FLOOR,
    FIRE_STONE, TILE_FIELD_YELLOW, TILE_FIELD_RED,
    TILE_FIELD_GREEN, TILE_FIELD_VIOLET, TILE_FIELD_BLUE,
    TEXTURE
}
